# Generated by Django 6.0.5 on 2026-05-13 15:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('id_card_front_url', models.URLField(blank=True, null=True)),
                ('id_card_back_url', models.URLField(blank=True, null=True)),
                ('selfie_url', models.URLField(blank=True, null=True)),
                ('kyc_status', models.CharField(default='PENDING', max_length=20)),
                ('is_suspended', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operator', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chips', to='core.agent')),
            ],
            options={
                'unique_together': {('agent', 'operator', 'phone_number')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('target_operator', models.CharField(max_length=50)),
                ('target_phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_sic', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('agent_benefit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_compensated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.agent')),
            ],
        ),
        migrations.CreateModel(
            name='CompensationDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_deducted', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('cinetpay_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_details', to='core.chip')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_details', to='core.transaction')),
            ],
        ),
    ]
