# Generated by Django 6.0.5 on 2026-05-16 11:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_activitylog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chip',
            new_name='Puce',
        ),
        migrations.AlterField(
            model_name='compensationdetail',
            name='chip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_details', to='core.puce'),
        ),
    ]
