# Generated by Django 6.0.5 on 2026-05-16 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_puce_alter_compensationdetail_chip_delete_chip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compensationdetail',
            old_name='chip',
            new_name='puce',
        ),
        migrations.AlterField(
            model_name='puce',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puces', to='core.agent'),
        ),
    ]
