# Generated by Django 6.0.6 on 2026-06-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_agent_pin_biometric_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puce',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
