# Generated by Django 6.0.6 on 2026-06-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_puce_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='account_type',
            field=models.CharField(choices=[('AGENT', 'Agent'), ('CLIENT', 'Client')], default='AGENT', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
