# Generated by Django 6.0.6 on 2026-06-14 11:42

from django.db import migrations, models


def set_tier_from_status(apps, schema_editor):
    """Compat ascendante : les agents deja APPROVED passent au palier complet
    (2) pour conserver leurs limites actuelles (illimitees). Les autres restent
    au palier 0 (Starter, plafonne)."""
    Agent = apps.get_model('core', 'Agent')
    Agent.objects.filter(kyc_status='APPROVED').update(kyc_tier=2)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_agent_account_type_transaction_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='kyc_tier',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.RunPython(set_tier_from_status, noop),
    ]
