# Generated by Django 6.0.6 on 2026-06-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_trusteddevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='kyc_rejection_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='agent',
            name='kyc_requested_tier',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='kyc_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='id_card_back_url',
            field=models.FileField(blank=True, null=True, upload_to='kyc/'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='id_card_front_url',
            field=models.FileField(blank=True, null=True, upload_to='kyc/'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='selfie_url',
            field=models.FileField(blank=True, null=True, upload_to='kyc/'),
        ),
    ]
