# Generated by Django 6.0.6 on 2026-06-15 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_agent_kyc_rejection_reason_agent_kyc_requested_tier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='agent_benefit',
        ),
    ]
