# Generated by Django 6.0.6 on 2026-06-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_transaction_agent_benefit'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='merchant_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
