# Generated by Django 6.0.6 on 2026-06-18 16:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_agent_merchant_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('threshold', models.DecimalField(decimal_places=2, default=50000, max_digits=12)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('puce', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert_config', to='core.puce')),
            ],
        ),
    ]
