# Generated by Django 6.0.6 on 2026-06-18 16:25

from django.db import migrations


def create_missing_alert_configs(apps, schema_editor):
    """Cree une alerte de solde par defaut pour les puces existantes."""
    Puce = apps.get_model('core', 'Puce')
    AlertConfig = apps.get_model('core', 'AlertConfig')
    for puce in Puce.objects.filter(alert_config__isnull=True):
        AlertConfig.objects.create(puce=puce)


def remove_alert_configs(apps, schema_editor):
    """Reversible : supprime toutes les alertes (le schema part avec 0015)."""
    AlertConfig = apps.get_model('core', 'AlertConfig')
    AlertConfig.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alertconfig'),
    ]

    operations = [
        migrations.RunPython(
            create_missing_alert_configs, remove_alert_configs
        ),
    ]
