# Generated by Django 6.0.6 on 2026-06-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_backfill_alert_configs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compensationdetail',
            name='cinetpay_ref',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='compensationdetail',
            index=models.Index(fields=['status'], name='core_compen_status_6d3d4e_idx'),
        ),
        migrations.AddIndex(
            model_name='puce',
            index=models.Index(fields=['agent', 'is_active'], name='core_puce_agent_i_34beec_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['agent', '-created_at'], name='core_transa_agent_i_05be1b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='core_transa_status_288ab7_idx'),
        ),
    ]
